-- Create player_snapshots table
CREATE TABLE player_snapshots (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  snapshot_date DATE NOT NULL,
  player_id INTEGER NOT NULL,
  player_name TEXT NOT NULL,
  team_id INTEGER,
  team_abbreviation TEXT,
  age INTEGER,
  gp INTEGER,
  min DECIMAL(5,1),
  pts DECIMAL(5,1),
  fgm DECIMAL(5,1),
  fga DECIMAL(5,1),
  fg_pct DECIMAL(4,3),
  fg3m DECIMAL(5,1),
  fg3a DECIMAL(5,1),
  fg3_pct DECIMAL(4,3),
  ftm DECIMAL(5,1),
  fta DECIMAL(5,1),
  ft_pct DECIMAL(4,3),
  reb DECIMAL(5,1),
  ast DECIMAL(5,1),
  stl DECIMAL(5,1),
  blk DECIMAL(5,1),
  tov DECIMAL(5,1),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(snapshot_date, player_id)
);